spring:
  application:
    name: inventory

server:
  port: 8082

eureka:
  instance:
    preferIpAddress: false
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://eureka-service:8070/eureka
      
hello-server:
     ribbon:
       listOfServers: http://hello-server:8071

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


